name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Ensure this region is correct

    - name: Log in to AWS ECR
      id: ecr_login
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1  # Ensure the region is correct

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Set output for image tag
      id: image_tag
      run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV  # Use dynamic tag if needed
