name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust region as needed

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var "image_tag=${{ secrets.IMAGE_TAG }}"  # Pass IMAGE_TAG secret here

    - name: Terraform Apply
      run: terraform apply -auto-approve -var "image_tag=${{ secrets.IMAGE_TAG }}"  # Apply the changes using IMAGE_TAG

    - name: Output EC2 Public IP
      run: echo "EC2 Public IP: ${{ steps.terraform_apply.outputs.ec2_public_ip }}"
