
name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var "image_tag=${{ env.IMAGE_TAG }}" 

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -var "image_tag=${{ env.IMAGE_TAG }}"

    - name: Output EC2 Public IP
      run: |
        echo "Fetching EC2 Public IP from Terraform outputs..."
        terraform output ec2_public_ip
